name: C++ Portfolio CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4 # This checks out *this* repository (cpp_portfolio)
      with:
        path: cpp_portfolio # Check it out into a folder named cpp_portfolio

    - name: Checkout vcpkg
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg # Specify the vcpkg repository
        path: vcpkg # Check out vcpkg into a folder named vcpkg at the root of the runner's workspace

    - name: Bootstrap vcpkg
      run: cmd /c vcpkg/bootstrap-vcpkg.bat # Path to vcpkg from the workspace root

    - name: Install vcpkg dependencies
      run: cmd /c vcpkg/vcpkg.exe install boost protobuf spdlog abseil nlohmann-json --triplet x64-windows

    - name: Configure CMake for Windows
      run: cmake -G "Visual Studio 17 2022" -S cpp_portfolio -B cpp_portfolio/build -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build with CMake for Windows
      run: cmake --build cpp_portfolio/build --config Release

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update Homebrew
      run: brew update

    - name: Run Homebrew Doctor
      run: brew doctor

    - name: Install dependencies with Homebrew
      run: brew install boost protobuf spdlog abseil-cpp nlohmann-json cmake

    - name: Configure CMake for macOS
      run: cmake -S cpp_portfolio -B cpp_portfolio/build

    - name: Build with CMake for macOS
      run: cmake --build cpp_portfolio/build --config Release

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update apt-get
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake libboost-all-dev libprotobuf-dev protobuf-compiler libspdlog-dev libyaml-cpp-dev nlohmann-json3-dev

    - name: Configure CMake for Linux
      run: cmake -S cpp_portfolio -B cpp_portfolio/build -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake for Linux
      run: cmake --build cpp_portfolio/build --config Release